<?php
/**
 * @file
 * Os2subsites module file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter() for the taxonomy term form.
 */
function bc_subsites_form_subsite_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\bc_subsites\SubsiteInterface $subsite */
  $subsite = $form_state->getFormObject()->getEntity();
  if (!$subsite->isNew()) {
    $form['profile']['#disabled'] = TRUE;
  }
}
